#!/usr/bin/env bash

# Exit script if you try to use an uninitialized variable.
set -o nounset

echo "------ HOOK START - POST PUSH -------"

case "${DOCKER_TAG}" in
"5.6-cli-jessie")
	ALIAS="latest"
	;;
"dev-5.6-cli-jessie")
	ALIAS="dev"
	;;
*)
	exec 0
	;;
esac

docker tag "$IMAGE_NAME" "$DOCKER_REPO:$ALIAS"
docker push "$DOCKER_REPO:$ALIAS"

echo "------ HOOK END - POST PUSH -------"
