#!/usr/bin/env bash

# Exit script if you try to use an uninitialized variable.
set -o nounset

echo "------ HOOK START - POST PUSH -------"

case "${DOCKER_TAG}" in
"5.6-cli-jessie")
	aliases=(latest, 5.6-cli)
	;;
"dev-5.6-cli-jessie")
	aliases=(dev dev-5.6-cli)
	;;
"7.2-cli-jessie")
	aliases=(7.2-cli)
	;;
"dev-7.2-cli-jessie")
	aliases=(dev-7.2-cli)
	;;
esac

for alias in "${aliases[@]}"; do
	docker tag "$IMAGE_NAME" "$DOCKER_REPO:$alias"
	docker push "$DOCKER_REPO:$alias"
done

echo "------ HOOK END - POST PUSH -------"
