#!/usr/bin/env bash

# Exit script if you try to use an uninitialized variable.
set -o nounset

TAG=$(echo "${IMAGE_NAME}" | cut -d':' -f 2)

echo "------ HOOK START - POST PUSH -------"

alias="NULL"

case "${TAG}" in
"5.6-cli-jessie")
	alias="latest"
	;;
"dev-5.6-cli-jessie")
	alias="dev"
	;;
esac

if "${alias}" != "NULL"; then
	docker tag "$IMAGE_NAME" "$DOCKER_REPO:$alias"
	docker push "$DOCKER_REPO:$alias"
fi

echo "------ HOOK END - POST PUSH -------"
