FROM technomatix/php:5.6-cli-jessie

RUN set -xe && \
    apt-get -qq update && \

    # Install Tools
    apt-get -qq install --assume-yes jq unzip && \

    # Install ShellCheck
    curl --insecure -OL https://storage.googleapis.com/shellcheck/shellcheck-stable.linux.x86_64.tar.xz && \
    tar -xvf shellcheck-stable.linux.x86_64.tar.xz && \
    mv shellcheck-stable/shellcheck /usr/local/bin/shellcheck && \
    rm -fr shellcheck-stable shellcheck-stable.linux.x86_64.tar.xz && \

    # Install xDebug
    pecl install xdebug-2.5.5 && \
    docker-php-ext-enable xdebug && \
    echo "xdebug.remote_enable=on" | tee -a /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini && \
    echo "xdebug.remote_connect_back=on" | tee -a /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini && \

    # Install Bats
    git clone --depth 1 https://github.com/sstephenson/bats.git /tmp/bats && \
    cd /tmp/bats && \
    ./install.sh /usr/local && \

    # Install shfmt
    curl --fail --location https://github.com/mvdan/sh/releases/download/v2.6.3/shfmt_v2.6.3_linux_amd64 > /usr/local/bin/shfmt && \
    chmod +x /usr/local/bin/shfmt && \

    # Install Codeception
    composer global require --optimize-autoloader codeception/codeception && \

    # Install Sonar Scanner
    curl --insecure -OL https://sonarsource.bintray.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-3.1.0.1141-linux.zip && \
    unzip sonar-scanner-cli-3.1.0.1141-linux.zip  && \
    rm sonar-scanner-cli-3.1.0.1141-linux.zip  && \
    mv sonar-scanner-3.1.0.1141-linux /opt/sonar-scanner  && \

    # Clean
    composer clearcache && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

ENV PATH="/opt/sonar-scanner/bin:${PATH}"

ARG BUILD_DATE
ARG VCS_REF

LABEL org.label-schema.build-date=$BUILD_DATE \
      org.label-schema.vcs-ref=$VCS_REF
